### ISSUE TITLE
Relative time

### ISSUE THREAD

**Issue by henrikekblad** [G07cha/human-readable-time#7]
'%relative% ago' looks a bit weird for yesterday. 

Propose to change it to "1 day" ago instead.

**Comment by G07cha** [comment]
Hi @henrikekblad, thanks for your issue.

I might don't understood your idea correctly so let's make it clear.
You mean that "relative" feature should work like this? :arrow_down: 
```javascript
console.log(hrt(new Date(0), 'It was %relative%')); // -> It was 45 years ago
var yesterday = new Date(new Date().setDate(new Date().getDate() - 1));
console.log(hrt(yesterday, 'It was %relative%')); // -> It was yesterday

**Comment by henrikekblad** [comment]
Just noted that "yesterday" is problematic when using it together with a prefix/suffix.. like "It was" or "ago". 

I ended up using the "time-ago" library. Which was more suitable for my use case. You can close this issue if you want.


Thanks
Henrik

**Comment by perry-mitchell** [comment]
I also feel that "Yesterday" is problematic, for the same reason. Suffixing "ago" works for all time periods besides 1 day ago, which is awkwardly presented as "yesterday" (and therefore "yesterday ago").

**Comment by perry-mitchell** [comment]
I created a PR to address this - #10
